# Generated by Django 5.1.6 on 2025-02-08 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_hospitals_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospitals',
            name='image',
            field=models.ImageField(upload_to='api/images/hosptials'),
        ),
    ]
