# Generated by Django 5.1.6 on 2025-02-08 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_hospitals_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospitals',
            name='description',
            field=models.TextField(blank=True, max_length=1000),
        ),
    ]
